language: python
python:
  - 3.6
sudo: required
services:
  - docker
before_install:
  - make build
jobs:
  include:
  - stage: check
    if: type = pull_request
    script: make pull-cache lint test
  - stage: deploy  
    if: type != pull_request and branch = master
    script: make pull-cache build push
