---
language: python
python:
  - 3.6
cache: pip
services:
  - docker
install:
  - pip install -r app/requirements.txt  # needed for tests
jobs:
  include:
    - stage: check
      if: type = pull_request
      script: make pull-cache lint test
    - stage: deploy
      if: type != pull_request and branch = master
      script: make pull-cache build push
