sudo: required
services:
  - docker
before_install:
  - make build
script: make lint test
# jobs:
#   include:
#   - if: type = pull_request AND branch != master
#     script: make lint test
#   - if: type != pull_request and branch = master
#     script: make push
