"""
The models defined here can be used to autogenerate alembic migrations
using the make auto-revision target.
"""

from sqlalchemy import (
    Column,
    Date,
    Float,
    Integer,
    String,
    Text,
    Time
)
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class Game(Base):
    __tablename__ = 'games'

    type = Column(String(16), autoincrement=False, nullable=False)
    game_id = Column(Integer, autoincrement=False, nullable=False, primary_key=True)
    home_team = Column(String(16), autoincrement=False, nullable=False)
    away_team = Column(String(16), autoincrement=False, nullable=False)
    week = Column(Integer, autoincrement=False, nullable=False)
    season = Column(Integer, autoincrement=False, nullable=False)
    state_of_game = Column(String(16), autoincrement=False, nullable=False)
    game_url = Column(String(255), autoincrement=False, nullable=False)
    home_score = Column(Integer, autoincrement=False, nullable=True)
    away_score = Column(Integer, autoincrement=False, nullable=True)

    def __repr__(self):
        return f"<Game((H) {self.home_team} {self.home_score} - {self.away_score} {self.away_team} (A))>"


class PlayByPlay(Base):
    __tablename__ = 'play_by_play'

    play_id = Column(Integer, nullable=False, primary_key=True)
    game_id = Column(Integer, nullable=False, primary_key=True)
    home_team = Column(String(16), nullable=False)
    away_team = Column(String(16), nullable=False)
    posteam = Column(String(16))
    posteam_type = Column(String(16))
    defteam = Column(String(16))
    side_of_field = Column(String(16))
    yardline_100 = Column(Integer)
    game_date = Column(Date,)
    quarter_seconds_remaining = Column(Integer)
    half_seconds_remaining = Column(Integer)
    game_seconds_remaining = Column(Integer)
    game_half = Column(String(16))
    quarter_end = Column(Integer)
    drive = Column(Integer)
    sp = Column(Integer)
    qtr = Column(Integer)
    down = Column(Integer)
    goal_to_go = Column(Integer)
    time = Column(Time)
    yrdln = Column(String(16))
    ydstogo = Column(Integer)
    ydsnet = Column(Integer)
    desc = Column(Text)
    play_type = Column(Text)
    yards_gained = Column(Integer)
    shotgun = Column(Integer)
    no_huddle = Column(Integer)
    qb_dropback = Column(Integer)
    qb_kneel = Column(Integer)
    qb_spike = Column(Integer)
    qb_scramble = Column(Integer)
    pass_length = Column(String(16))
    pass_location = Column(String(16))
    air_yards = Column(Integer)
    yards_after_catch = Column(Integer)
    run_location = Column(String(16))
    run_gap = Column(String(16))
    field_goal_result = Column(String(16))
    kick_distance = Column(Integer)
    extra_point_result = Column(String(16))
    two_point_conv_result = Column(String(16))
    home_timeouts_remaining = Column(Integer)
    away_timeouts_remaining = Column(Integer)
    timeout = Column(Integer)
    timeout_team = Column(String(16))
    td_team = Column(String(16))
    posteam_timeouts_remaining = Column(Integer)
    defteam_timeouts_remaining = Column(Integer)
    total_home_score = Column(Integer)
    total_away_score = Column(Integer)
    posteam_score = Column(Integer)
    defteam_score = Column(Integer)
    score_differential = Column(Integer)
    posteam_score_post = Column(Integer)
    defteam_score_post = Column(Integer)
    score_differential_post = Column(Integer)
    no_score_prob = Column(Float)
    opp_fg_prob = Column(Float)
    opp_safety_prob = Column(Float)
    opp_td_prob = Column(Float)
    fg_prob = Column(Float)
    safety_prob = Column(Float)
    td_prob = Column(Float)
    extra_point_prob = Column(Float)
    two_point_conversion_prob = Column(Float)
    ep = Column(Float)
    epa = Column(Float)
    total_home_epa = Column(Float)
    total_away_epa = Column(Float)
    total_home_rush_epa = Column(Float)
    total_away_rush_epa = Column(Float)
    total_home_pass_epa = Column(Float)
    total_away_pass_epa = Column(Float)
    air_epa = Column(Float)
    yac_epa = Column(Float)
    comp_air_epa = Column(Float)
    comp_yac_epa = Column(Float)
    total_home_comp_air_epa = Column(Float)
    total_away_comp_air_epa = Column(Float)
    total_home_comp_yac_epa = Column(Float)
    total_away_comp_yac_epa = Column(Float)
    total_home_raw_air_epa = Column(Float)
    total_away_raw_air_epa = Column(Float)
    total_home_raw_yac_epa = Column(Float)
    total_away_raw_yac_epa = Column(Float)
    wp = Column(Float)
    def_wp = Column(Float)
    home_wp = Column(Float)
    away_wp = Column(Float)
    wpa = Column(Float)
    home_wp_post = Column(Float)
    away_wp_post = Column(Float)
    total_home_rush_wpa = Column(Float)
    total_away_rush_wpa = Column(Float)
    total_home_pass_wpa = Column(Float)
    total_away_pass_wpa = Column(Float)
    air_wpa = Column(Float)
    yac_wpa = Column(Float)
    comp_air_wpa = Column(Float)
    comp_yac_wpa = Column(Float)
    total_home_comp_air_wpa = Column(Float)
    total_away_comp_air_wpa = Column(Float)
    total_home_comp_yac_wpa = Column(Float)
    total_away_comp_yac_wpa = Column(Float)
    total_home_raw_air_wpa = Column(Float)
    total_away_raw_air_wpa = Column(Float)
    total_home_raw_yac_wpa = Column(Float)
    total_away_raw_yac_wpa = Column(Float)
    punt_blocked = Column(Integer)
    first_down_rush = Column(Integer)
    first_down_pass = Column(Integer)
    first_down_penalty = Column(Integer)
    third_down_converted = Column(Integer)
    third_down_failed = Column(Integer)
    fourth_down_converted = Column(Integer)
    fourth_down_failed = Column(Integer)
    incomplete_pass = Column(Integer)
    touchback = Column(Integer)
    interception = Column(Integer)
    punt_inside_twenty = Column(Integer)
    punt_in_endzone = Column(Integer)
    punt_out_of_bounds = Column(Integer)
    punt_downed = Column(Integer)
    punt_fair_catch = Column(Integer)
    kickoff_inside_twenty = Column(Integer)
    kickoff_in_endzone = Column(Integer)
    kickoff_out_of_bounds = Column(Integer)
    kickoff_downed = Column(Integer)
    kickoff_fair_catch = Column(Integer)
    fumble_forced = Column(Integer)
    fumble_not_forced = Column(Integer)
    fumble_out_of_bounds = Column(Integer)
    solo_tackle = Column(Integer)
    safety = Column(Integer)
    penalty = Column(Integer)
    tackled_for_loss = Column(Integer)
    fumble_lost = Column(Integer)
    own_kickoff_recovery = Column(Integer)
    own_kickoff_recovery_td = Column(Integer)
    qb_hit = Column(Integer)
    rush_attempt = Column(Integer)
    pass_attempt = Column(Integer)
    sack = Column(Integer)
    touchdown = Column(Integer)
    pass_touchdown = Column(Integer)
    rush_touchdown = Column(Integer)
    return_touchdown = Column(Integer)
    extra_point_attempt = Column(Integer)
    two_point_attempt = Column(Integer)
    field_goal_attempt = Column(Integer)
    kickoff_attempt = Column(Integer)
    punt_attempt = Column(Integer)
    fumble = Column(Integer)
    complete_pass = Column(Integer)
    assist_tackle = Column(Integer)
    lateral_reception = Column(Integer)
    lateral_rush = Column(Integer)
    lateral_return = Column(Integer)
    lateral_recovery = Column(Integer)
    passer_player_id = Column(Text)
    passer_player_name = Column(String(64))
    receiver_player_id = Column(Text)
    receiver_player_name = Column(String(64))
    rusher_player_id = Column(Text)
    rusher_player_name = Column(String(64))
    lateral_receiver_player_id = Column(Text)
    lateral_receiver_player_name = Column(String(64))
    lateral_rusher_player_id = Column(Text)
    lateral_rusher_player_name = Column(String(64))
    lateral_sack_player_id = Column(Text)
    lateral_sack_player_name = Column(String(64))
    interception_player_id = Column(Text)
    interception_player_name = Column(String(64))
    lateral_interception_player_id = Column(Text)
    lateral_interception_player_name = Column(String(64))
    punt_returner_player_id = Column(Text)
    punt_returner_player_name = Column(String(64))
    lateral_punt_returner_player_id = Column(Text)
    lateral_punt_returner_player_name = Column(String(64))
    kickoff_returner_player_name = Column(String(64))
    kickoff_returner_player_id = Column(Text)
    lateral_kickoff_returner_player_id = Column(Text)
    lateral_kickoff_returner_player_name = Column(String(64))
    punter_player_id = Column(Text)
    punter_player_name = Column(String(64))
    kicker_player_name = Column(String(64))
    kicker_player_id = Column(Text)
    own_kickoff_recovery_player_id = Column(Text)
    own_kickoff_recovery_player_name = Column(String(64))
    blocked_player_id = Column(Text)
    blocked_player_name = Column(String(64))
    tackle_for_loss_1_player_id = Column(Text)
    tackle_for_loss_1_player_name = Column(String(64))
    tackle_for_loss_2_player_id = Column(Text)
    tackle_for_loss_2_player_name = Column(String(64))
    qb_hit_1_player_id = Column(Text)
    qb_hit_1_player_name = Column(String(64))
    qb_hit_2_player_id = Column(Text)
    qb_hit_2_player_name = Column(String(64))
    forced_fumble_player_1_team = Column(String(16))
    forced_fumble_player_1_player_id = Column(Text)
    forced_fumble_player_1_player_name = Column(String(64))
    forced_fumble_player_2_team = Column(String(16))
    forced_fumble_player_2_player_id = Column(Text)
    forced_fumble_player_2_player_name = Column(String(64))
    solo_tackle_1_team = Column(String(16))
    solo_tackle_2_team = Column(String(16))
    solo_tackle_1_player_id = Column(Text)
    solo_tackle_2_player_id = Column(Text)
    solo_tackle_1_player_name = Column(String(64))
    solo_tackle_2_player_name = Column(String(64))
    assist_tackle_1_player_id = Column(Text)
    assist_tackle_1_player_name = Column(String(64))
    assist_tackle_1_team = Column(String(16))
    assist_tackle_2_player_id = Column(Text)
    assist_tackle_2_player_name = Column(String(64))
    assist_tackle_2_team = Column(String(16))
    assist_tackle_3_player_id = Column(Text)
    assist_tackle_3_player_name = Column(String(64))
    assist_tackle_3_team = Column(String(16))
    assist_tackle_4_player_id = Column(Text)
    assist_tackle_4_player_name = Column(String(64))
    assist_tackle_4_team = Column(String(16))
    pass_defense_1_player_id = Column(Text)
    pass_defense_1_player_name = Column(String(64))
    pass_defense_2_player_id = Column(Text)
    pass_defense_2_player_name = Column(String(64))
    fumbled_1_team = Column(String(16))
    fumbled_1_player_id = Column(Text)
    fumbled_1_player_name = Column(String(64))
    fumbled_2_player_id = Column(Text)
    fumbled_2_player_name = Column(String(64))
    fumbled_2_team = Column(String(16))
    fumble_recovery_1_team = Column(String(16))
    fumble_recovery_1_yards = Column(Integer)
    fumble_recovery_1_player_id = Column(Text)
    fumble_recovery_1_player_name = Column(String(64))
    fumble_recovery_2_team = Column(String(16))
    fumble_recovery_2_yards = Column(Integer)
    fumble_recovery_2_player_id = Column(Text)
    fumble_recovery_2_player_name = Column(String(64))
    return_team = Column(String(16))
    return_yards = Column(Integer)
    penalty_team = Column(String(16))
    penalty_player_id = Column(Text)
    penalty_player_name = Column(String(64))
    penalty_yards = Column(Integer)
    replay_or_challenge = Column(Integer)
    replay_or_challenge_result = Column(String(32))
    penalty_type = Column(String(64))
    defensive_two_point_attempt = Column(Integer)
    defensive_two_point_conv = Column(Integer)
    defensive_extra_point_attempt = Column(Integer)
    defensive_extra_point_conv = Column(Integer)
