"""create_games_table

Revision ID: f323433bd52a
Revises: 
Create Date: 2019-12-19 20:45:31.133769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f323433bd52a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('type', sa.String(length=16), autoincrement=False, nullable=False),
    sa.Column('game_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('home_team', sa.String(length=16), autoincrement=False, nullable=False),
    sa.Column('away_team', sa.String(length=16), autoincrement=False, nullable=False),
    sa.Column('week', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('season', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('state_of_game', sa.String(length=16), autoincrement=False, nullable=False),
    sa.Column('game_url', sa.String(length=255), autoincrement=False, nullable=False),
    sa.Column('home_score', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('away_score', sa.Integer(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('game_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    # ### end Alembic commands ###
